### ISSUE TITLE
SSLv3 alert handshake failure

### ISSUE THREAD

**Issue by petrcermak** [chromium/web-page-replay#73]
How to reproduce:

1. Run <tt>third\_party/webpagereplay/replay.py --port 0 --ssl\_port 0 --no-dns\_forwarding --use\_closest\_match -r foo.wpr</tt>
2. Run <tt>/opt/google/chrome/chrome --no-default-browser-check --no-first-run --ignore-certificate-errors --host-resolver-rules="MAP * 127.0.0.1,EXCLUDE localhost" --testing-fixed-http-port=*HTTPS\_PORT* --testing-fixed-https-port=*HTTP\_PORT* --no-proxy-server --user-data-dir=$(mktemp -d)</tt> in a separate terminal with <tt>*HTTP\_PORT*</tt> and <tt>*HTTPS\_PORT*</tt> taken from the output of the first command.
3. Go to https://i1.sndcdn.com/artworks-000139618215-ubm1i6-t500x500.jpg.

The page fails to load ("404 Not Found") and <tt>replay.py</tt> generates the following output:

```
2016-05-11 10:51:40,076 DEBUG RealHttpFetch: i1.sndcdn.com /artworks-000139618215-ubm1i6-t500x500.jpg
2016-05-11 10:51:40,427 WARNING Retrying fetch GET https://i1.sndcdn.com/artworks-000139618215-ubm1i6-t500x500.jpg [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com'), ('upgrade-insecure-requests', '1')]: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
2016-05-11 10:51:40,443 WARNING Retrying fetch GET https://i1.sndcdn.com/artworks-000139618215-ubm1i6-t500x500.jpg [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com'), ('upgrade-insecure-requests', '1')]: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
2016-05-11 10:51:40,460 WARNING Retrying fetch GET https://i1.sndcdn.com/artworks-000139618215-ubm1i6-t500x500.jpg [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com'), ('upgrade-insecure-requests', '1')]: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
2016-05-11 10:51:40,476 CRITICAL Could not fetch GET https://i1.sndcdn.com/artworks-000139618215-ubm1i6-t500x500.jpg [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com'), ('upgrade-insecure-requests', '1')]: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
2016-05-11 10:51:40,476 WARNING Failed to find response for: GET https://i1.sndcdn.com/artworks-000139618215-ubm1i6-t500x500.jpg [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com'), ('upgrade-insecure-requests', '1')] (401ms)
2016-05-11 10:51:40,556 DEBUG RealHttpFetch: i1.sndcdn.com /favicon.ico
2016-05-11 10:51:40,573 WARNING Retrying fetch GET https://i1.sndcdn.com/favicon.ico [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com')]: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
2016-05-11 10:51:40,592 WARNING Retrying fetch GET https://i1.sndcdn.com/favicon.ico [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com')]: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
2016-05-11 10:51:40,608 WARNING Retrying fetch GET https://i1.sndcdn.com/favicon.ico [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com')]: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
2016-05-11 10:51:40,628 CRITICAL Could not fetch GET https://i1.sndcdn.com/favicon.ico [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com')]: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
2016-05-11 10:51:40,628 WARNING Failed to find response for: GET https://i1.sndcdn.com/favicon.ico [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com')] (73ms)
```

Accessing the same image via http (http://i1.sndcdn.com/artworks-000139618215-ubm1i6-t500x500.jpg) works absolutely fine:

```
2016-05-11 10:52:18,407 DEBUG RealHttpFetch: i1.sndcdn.com /artworks-000139618215-ubm1i6-t500x500.jpg
2016-05-11 10:52:18,456 DEBUG Recorded: GET http://i1.sndcdn.com/artworks-000139618215-ubm1i6-t500x500.jpg [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com'), ('upgrade-insecure-requests', '1')]
2016-05-11 10:52:18,457 DEBUG Served: GET http://i1.sndcdn.com/artworks-000139618215-ubm1i6-t500x500.jpg [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com'), ('upgrade-insecure-requests', '1')] (50ms)
2016-05-11 10:52:18,539 DEBUG RealHttpFetch: i1.sndcdn.com /favicon.ico
2016-05-11 10:52:18,645 DEBUG Recorded: GET http://i1.sndcdn.com/favicon.ico [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com')]
2016-05-11 10:52:18,646 DEBUG Served: GET http://i1.sndcdn.com/favicon.ico [('accept-encoding', 'gzip,deflate'), ('host', 'i1.sndcdn.com')] (108ms)
```

**Comment by petrcermak** [comment]
It seems that the problem is due to an old version of OpenSSL (https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning).

**Comment by nedn** [comment]
Looks like force using python2.7.9 is not a good solution since most machine have python 2.7.9. A proposed solution from @nickie is to package [pyopenssl](https://github.com/pyca/pyopenssl) in third_party/ instead.

**Comment by dtrebbien** [comment]
I can reproduce this issue on Mac OS X Version 10.11.5 (15F34), running Python 2.7.11 installed via Homebrew. I have checked, and the ssl library is using Homebrew's OpenSSL (version 1.0.2h as of this writing):

```python
import ssl
print ssl.OPENSSL_VERSION
```

Thus, it does not appear to be an issue with an old version of OpenSSL.

**Comment by nedn** [comment]
Ok, I have more time to dig into this today. For the case of loading theverge.com, it looks like this is not an issue with  an old version of OpenSSL but the https request we issue to the server. In particular, the header may cause SSL failure.

This is the minimal reproducible:

`import httplib

connection = httplib.HTTPSConnection('tags.api.umbel.com')
headers = {
  'accept-language': 'en-US,en;q=0.8',
  'accept-encoding': 'gzip,deflate,br',
  'connection': 'keep-alive',
  'accept': 'image/webp,image/*,*/*;q=0.8',
  'user-agent': 'Mozilla/5.0 (Macintosh;Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2793.0 Safari/537.36',
  'host': 'm3jnlukh12.execute-api.us-east-1.amazonaws.com',
  'referer': 'http://www.theverge.com/2015/6/5/8727399/parrot-bebop-drone-review',
  'cache-control': 'max-age=0'
}

# RETURN {"message":"Forbidden"}
connection.request('GET', '/lrjhazrpqbgtnrij/w.js', headers=headers)
response = connection.getresponse()
print response.read()

# RETURN ACTUAL JS CONTENT
connection.request('GET', '/lrjhazrpqbgtnrij/w.js', headers={})
response = connection.getresponse()
print response.read()`

**Comment by nedn** [comment]
Please ignore my comment above, after digging more, the root cause is because we translate the string host name to ip address in https://github.com/chromium/web-page-replay/blob/7142ee71f87f300bcd325b516c18d33912915952/httpclient.py#L298 

> `# Use an IP address because WPR may override DNS settings.`
> ` connection_ip = self._real_dns_lookup(connection_host)`

To reproduce this bug:
`import httplib`
`connection = httplib.HTTPSConnection('tags.api.umbel.com')`
`connection.connect()  # OK`

`connection = httplib.HTTPSConnection('52.85.209.188')  # The IP address of tags.api.umbel.com `
`connection.connect()  # ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590) got thrown`

I believe fix here is to not translate the string host name to ip address.  WPR shouldn't override DNS setting on recording mode.

**Comment by nedn** [comment]
FYI: @pasko @gabadie

**Comment by nedn** [comment]
Another problem while fetching HTTPS:
`import httplib`
`connection = httplib.HTTPSConnection('sdk.streamrail.com')`
`connection.connect()`
`connection.request('GET', '/player/sr.ads.js')`

Running the above yields:
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    connection.connect()
  File "/usr/lib/python2.7/httplib.py", line 1182, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

On the other hand, once can navigate to https://sdk.streamrail.com/player/sr.ads.js with no problem on Chrome. (Though navigating to https://sdk.streamrail.com/ return a 403)

**Comment by pmeenan** [comment]
Might not be the root cause but support for SSLv3 is being disabled across the web and it looks like the default HTTPSConnection implementation doesn't use TLS.

Here is a gist that looks like it does what you need: https://gist.github.com/flandr/74be22d1c3d7c1dfefdd

I'll try quickly in your test above to see if it helps.

**Comment by pmeenan** [comment]
Argh, I can't reproduce the problem on my main dev machine (Windows).  Let me know if the gist doesn't help and I can try on my Mac at home tonight.

**Comment by nedn** [comment]
I just try it & still has the problem:
```
import httplib
import urllib2
import socket
import ssl

class TLS1Connection(httplib.HTTPSConnection):
    """Like HTTPSConnection but more specific"""
    def __init__(self, host, **kwargs):
        httplib.HTTPSConnection.__init__(self, host, **kwargs)

    def connect(self):
        """Overrides HTTPSConnection.connect to specify TLS version"""
        # Standard implementation from HTTPSConnection, which is not
        # designed for extension, unfortunately
        sock = socket.create_connection((self.host, self.port),
                self.timeout, self.source_address)
        if getattr(self, '_tunnel_host', None):
            self.sock = sock
            self._tunnel()

        # This is the only difference; default wrap_socket uses SSLv23
        self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file,
                ssl_version=ssl.PROTOCOL_TLSv1)

class TLS1Handler(urllib2.HTTPSHandler):
    """Like HTTPSHandler but more specific"""
    def __init__(self):
        urllib2.HTTPSHandler.__init__(self)

    def https_open(self, req):
        return self.do_open(TLS1Connection, req)


# Override default handler
urllib2.install_opener(urllib2.build_opener(TLS1Handler()))


connection = TLS1Connection('sdk.streamrail.com')
connection.connect()
connection.request('GET', '/player/sr.ads.js')
res = connection.getresponse()

print res.read()
```
Traceback (most recent call last):
  File "test.py", line 39, in <module>
    connection.connect()
  File "test.py", line 23, in connect
    ssl_version=ssl.PROTOCOL_TLSv1)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure


Also it's worth noting that we don't have this problem with http.client lib in python3.

**Comment by pmeenan** [comment]
I'll fire up a VM and see if I can reproduce it.

I wouldn't be surprised if it was still an issue with the TLS config and TLSv1 may not be good enough.  TLS v 1.0 is also turned off in a lot of places though not everywhere might support 1.2.

In this case cloudfront appears to support TLS 1.0 -> 1.2 so I'm surprised it didn't work but maybe something else is causing the failure: https://www.ssllabs.com/ssltest/analyze.html?d=sdk.streamrail.com&s=52.85.209.112&latest

A tcpdump may help identify what option is causing the failure.

**Comment by pmeenan** [comment]
Sorry, did you really mean python 2.7.6?  As far as I can tell, SNI and a lot of other things are broken pre-2.7.9 so you're going to want that as a minimum.

**Comment by nedn** [comment]
Thanks, I will try python2.7.9 to see if it fixes the problem. The challenges is most of the bots on chromium still use python2.7.6, hence I had to revert https://github.com/chromium/web-page-replay/commit/03de0c5863e60943145df2b7bf93ee5bcb534048

If switching python to 2.7.9 is the fix, probably I will enforce python2.7.9 only for recording mode.

**Comment by pmeenan** [comment]
Maybe I'm missing something but on Ubuntu 16.0.4 with Python 2.7.10 this works fine:

```
import httplib
connection = httplib.HTTPSConnection('sdk.streamrail.com')
connection.connect()
request = connection.request('GET', '/player/sr.ads.js')
response = connection.getresponse()
print response.read()
```

Python < 2.7.9 isn't going to work with any server that needs SNI and it looks like protocol negotiation is working fine otherwise.

**Comment by nedn** [comment]
Thanks Patrick, I confirm that updating the python version to 2.7.9+ is the solution to fetch these https URL. I will make a change to throw exception when people try recording WPR with python version < 2.7.9

**Comment by nedn** [comment]
I verified that we can now load https://i1.sndcdn.com/artworks-000139618215-ubm1i6-t500x500.jpg on webpagereplay recording.
